project:
  type: website

website:
  title: "Abdubidopsis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects/index.qmd
        text: Projects
  page-footer:
    right: "Version: 2026-04-02"

format:
  html:
    theme: litera
    css: styles.css
    toc: false

editor: visual
